# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: extensions/v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class UnversionedStatusDetails(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Name=None, Group=None, Kind=None, Causes=None, RetryAfterSeconds=None):
        """
        UnversionedStatusDetails - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Name': 'str',
            'Group': 'str',
            'Kind': 'str',
            'Causes': 'list[UnversionedStatusCause]',
            'RetryAfterSeconds': 'int'
        }

        self.attribute_map = {
            'Name': 'name',
            'Group': 'group',
            'Kind': 'kind',
            'Causes': 'causes',
            'RetryAfterSeconds': 'retryAfterSeconds'
        }

        self._Name = Name
        self._Group = Group
        self._Kind = Kind
        self._Causes = Causes
        self._RetryAfterSeconds = RetryAfterSeconds

    @property
    def Name(self):
        """
        Gets the Name of this UnversionedStatusDetails.
        The name attribute of the resource associated with the status StatusReason (when there is a single name which can be described).

        :return: The Name of this UnversionedStatusDetails.
        :rtype: str
        """
        return self._Name

    @Name.setter
    def Name(self, Name):
        """
        Sets the Name of this UnversionedStatusDetails.
        The name attribute of the resource associated with the status StatusReason (when there is a single name which can be described).

        :param Name: The Name of this UnversionedStatusDetails.
        :type: str
        """

        self._Name = Name

    @property
    def Group(self):
        """
        Gets the Group of this UnversionedStatusDetails.
        The group attribute of the resource associated with the status StatusReason.

        :return: The Group of this UnversionedStatusDetails.
        :rtype: str
        """
        return self._Group

    @Group.setter
    def Group(self, Group):
        """
        Sets the Group of this UnversionedStatusDetails.
        The group attribute of the resource associated with the status StatusReason.

        :param Group: The Group of this UnversionedStatusDetails.
        :type: str
        """

        self._Group = Group

    @property
    def Kind(self):
        """
        Gets the Kind of this UnversionedStatusDetails.
        The kind attribute of the resource associated with the status StatusReason. On some operations may differ from the requested resource Kind. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds

        :return: The Kind of this UnversionedStatusDetails.
        :rtype: str
        """
        return self._Kind

    @Kind.setter
    def Kind(self, Kind):
        """
        Sets the Kind of this UnversionedStatusDetails.
        The kind attribute of the resource associated with the status StatusReason. On some operations may differ from the requested resource Kind. More info: http://releases.k8s.io/HEAD/docs/devel/api-conventions.md#types-kinds

        :param Kind: The Kind of this UnversionedStatusDetails.
        :type: str
        """

        self._Kind = Kind

    @property
    def Causes(self):
        """
        Gets the Causes of this UnversionedStatusDetails.
        The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes.

        :return: The Causes of this UnversionedStatusDetails.
        :rtype: list[UnversionedStatusCause]
        """
        return self._Causes

    @Causes.setter
    def Causes(self, Causes):
        """
        Sets the Causes of this UnversionedStatusDetails.
        The Causes array includes more details associated with the StatusReason failure. Not all StatusReasons may provide detailed causes.

        :param Causes: The Causes of this UnversionedStatusDetails.
        :type: list[UnversionedStatusCause]
        """

        self._Causes = Causes

    @property
    def RetryAfterSeconds(self):
        """
        Gets the RetryAfterSeconds of this UnversionedStatusDetails.
        If specified, the time in seconds before the operation should be retried.

        :return: The RetryAfterSeconds of this UnversionedStatusDetails.
        :rtype: int
        """
        return self._RetryAfterSeconds

    @RetryAfterSeconds.setter
    def RetryAfterSeconds(self, RetryAfterSeconds):
        """
        Sets the RetryAfterSeconds of this UnversionedStatusDetails.
        If specified, the time in seconds before the operation should be retried.

        :param RetryAfterSeconds: The RetryAfterSeconds of this UnversionedStatusDetails.
        :type: int
        """

        self._RetryAfterSeconds = RetryAfterSeconds

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
