# coding: utf-8

"""
    

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: extensions/v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1FlockerVolumeSource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, datasetName=None, datasetUUID=None):
        """
        V1FlockerVolumeSource - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'datasetName': 'str',
            'datasetUUID': 'str'
        }

        self.attribute_map = {
            'datasetName': 'datasetName',
            'datasetUUID': 'datasetUUID'
        }

        self._datasetName = datasetName
        self._datasetUUID = datasetUUID

    @property
    def datasetName(self):
        """
        Gets the datasetName of this V1FlockerVolumeSource.
        Name of the dataset stored as metadata -> name on the dataset for Flocker should be considered as deprecated

        :return: The datasetName of this V1FlockerVolumeSource.
        :rtype: str
        """
        return self._datasetName

    @datasetName.setter
    def datasetName(self, datasetName):
        """
        Sets the datasetName of this V1FlockerVolumeSource.
        Name of the dataset stored as metadata -> name on the dataset for Flocker should be considered as deprecated

        :param datasetName: The datasetName of this V1FlockerVolumeSource.
        :type: str
        """

        self._datasetName = datasetName

    @property
    def datasetUUID(self):
        """
        Gets the datasetUUID of this V1FlockerVolumeSource.
        UUID of the dataset. This is unique identifier of a Flocker dataset

        :return: The datasetUUID of this V1FlockerVolumeSource.
        :rtype: str
        """
        return self._datasetUUID

    @datasetUUID.setter
    def datasetUUID(self, datasetUUID):
        """
        Sets the datasetUUID of this V1FlockerVolumeSource.
        UUID of the dataset. This is unique identifier of a Flocker dataset

        :param datasetUUID: The datasetUUID of this V1FlockerVolumeSource.
        :type: str
        """

        self._datasetUUID = datasetUUID

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
