# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: extensions/v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1ISCSIVolumeSource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, TargetPortal=None, Iqn=None, Lun=None, IscsiInterface=None, FsType=None, ReadOnly=None):
        """
        V1ISCSIVolumeSource - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'TargetPortal': 'str',
            'Iqn': 'str',
            'Lun': 'int',
            'IscsiInterface': 'str',
            'FsType': 'str',
            'ReadOnly': 'bool'
        }

        self.attribute_map = {
            'TargetPortal': 'targetPortal',
            'Iqn': 'iqn',
            'Lun': 'lun',
            'IscsiInterface': 'iscsiInterface',
            'FsType': 'fsType',
            'ReadOnly': 'readOnly'
        }

        self._TargetPortal = TargetPortal
        self._Iqn = Iqn
        self._Lun = Lun
        self._IscsiInterface = IscsiInterface
        self._FsType = FsType
        self._ReadOnly = ReadOnly

    @property
    def TargetPortal(self):
        """
        Gets the TargetPortal of this V1ISCSIVolumeSource.
        iSCSI target portal. The portal is either an IP or ip_addr:port if the port is other than default (typically TCP ports 860 and 3260).

        :return: The TargetPortal of this V1ISCSIVolumeSource.
        :rtype: str
        """
        return self._TargetPortal

    @TargetPortal.setter
    def TargetPortal(self, TargetPortal):
        """
        Sets the TargetPortal of this V1ISCSIVolumeSource.
        iSCSI target portal. The portal is either an IP or ip_addr:port if the port is other than default (typically TCP ports 860 and 3260).

        :param TargetPortal: The TargetPortal of this V1ISCSIVolumeSource.
        :type: str
        """

        self._TargetPortal = TargetPortal

    @property
    def Iqn(self):
        """
        Gets the Iqn of this V1ISCSIVolumeSource.
        Target iSCSI Qualified Name.

        :return: The Iqn of this V1ISCSIVolumeSource.
        :rtype: str
        """
        return self._Iqn

    @Iqn.setter
    def Iqn(self, Iqn):
        """
        Sets the Iqn of this V1ISCSIVolumeSource.
        Target iSCSI Qualified Name.

        :param Iqn: The Iqn of this V1ISCSIVolumeSource.
        :type: str
        """

        self._Iqn = Iqn

    @property
    def Lun(self):
        """
        Gets the Lun of this V1ISCSIVolumeSource.
        iSCSI target lun number.

        :return: The Lun of this V1ISCSIVolumeSource.
        :rtype: int
        """
        return self._Lun

    @Lun.setter
    def Lun(self, Lun):
        """
        Sets the Lun of this V1ISCSIVolumeSource.
        iSCSI target lun number.

        :param Lun: The Lun of this V1ISCSIVolumeSource.
        :type: int
        """

        self._Lun = Lun

    @property
    def IscsiInterface(self):
        """
        Gets the IscsiInterface of this V1ISCSIVolumeSource.
        Optional: Defaults to 'default' (tcp). iSCSI interface name that uses an iSCSI transport.

        :return: The IscsiInterface of this V1ISCSIVolumeSource.
        :rtype: str
        """
        return self._IscsiInterface

    @IscsiInterface.setter
    def IscsiInterface(self, IscsiInterface):
        """
        Sets the IscsiInterface of this V1ISCSIVolumeSource.
        Optional: Defaults to 'default' (tcp). iSCSI interface name that uses an iSCSI transport.

        :param IscsiInterface: The IscsiInterface of this V1ISCSIVolumeSource.
        :type: str
        """

        self._IscsiInterface = IscsiInterface

    @property
    def FsType(self):
        """
        Gets the FsType of this V1ISCSIVolumeSource.
        Filesystem type of the volume that you want to mount. Tip: Ensure that the filesystem type is supported by the host operating system. Examples: \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. More info: http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#iscsi

        :return: The FsType of this V1ISCSIVolumeSource.
        :rtype: str
        """
        return self._FsType

    @FsType.setter
    def FsType(self, FsType):
        """
        Sets the FsType of this V1ISCSIVolumeSource.
        Filesystem type of the volume that you want to mount. Tip: Ensure that the filesystem type is supported by the host operating system. Examples: \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified. More info: http://releases.k8s.io/HEAD/docs/user-guide/volumes.md#iscsi

        :param FsType: The FsType of this V1ISCSIVolumeSource.
        :type: str
        """

        self._FsType = FsType

    @property
    def ReadOnly(self):
        """
        Gets the ReadOnly of this V1ISCSIVolumeSource.
        ReadOnly here will force the ReadOnly setting in VolumeMounts. Defaults to false.

        :return: The ReadOnly of this V1ISCSIVolumeSource.
        :rtype: bool
        """
        return self._ReadOnly

    @ReadOnly.setter
    def ReadOnly(self, ReadOnly):
        """
        Sets the ReadOnly of this V1ISCSIVolumeSource.
        ReadOnly here will force the ReadOnly setting in VolumeMounts. Defaults to false.

        :param ReadOnly: The ReadOnly of this V1ISCSIVolumeSource.
        :type: bool
        """

        self._ReadOnly = ReadOnly

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
