# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: extensions/v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1PodSecurityContext(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, SeLinuxOptions=None, RunAsUser=None, RunAsNonRoot=None, SupplementalGroups=None, FsGroup=None):
        """
        V1PodSecurityContext - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'SeLinuxOptions': 'V1SELinuxOptions',
            'RunAsUser': 'int',
            'RunAsNonRoot': 'bool',
            'SupplementalGroups': 'list[int]',
            'FsGroup': 'int'
        }

        self.attribute_map = {
            'SeLinuxOptions': 'seLinuxOptions',
            'RunAsUser': 'runAsUser',
            'RunAsNonRoot': 'runAsNonRoot',
            'SupplementalGroups': 'supplementalGroups',
            'FsGroup': 'fsGroup'
        }

        self._SeLinuxOptions = SeLinuxOptions
        self._RunAsUser = RunAsUser
        self._RunAsNonRoot = RunAsNonRoot
        self._SupplementalGroups = SupplementalGroups
        self._FsGroup = FsGroup

    @property
    def SeLinuxOptions(self):
        """
        Gets the SeLinuxOptions of this V1PodSecurityContext.
        The SELinux context to be applied to all containers. If unspecified, the container runtime will allocate a random SELinux context for each container.  May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container.

        :return: The SeLinuxOptions of this V1PodSecurityContext.
        :rtype: V1SELinuxOptions
        """
        return self._SeLinuxOptions

    @SeLinuxOptions.setter
    def SeLinuxOptions(self, SeLinuxOptions):
        """
        Sets the SeLinuxOptions of this V1PodSecurityContext.
        The SELinux context to be applied to all containers. If unspecified, the container runtime will allocate a random SELinux context for each container.  May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container.

        :param SeLinuxOptions: The SeLinuxOptions of this V1PodSecurityContext.
        :type: V1SELinuxOptions
        """

        self._SeLinuxOptions = SeLinuxOptions

    @property
    def RunAsUser(self):
        """
        Gets the RunAsUser of this V1PodSecurityContext.
        The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container.

        :return: The RunAsUser of this V1PodSecurityContext.
        :rtype: int
        """
        return self._RunAsUser

    @RunAsUser.setter
    def RunAsUser(self, RunAsUser):
        """
        Sets the RunAsUser of this V1PodSecurityContext.
        The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence for that container.

        :param RunAsUser: The RunAsUser of this V1PodSecurityContext.
        :type: int
        """

        self._RunAsUser = RunAsUser

    @property
    def RunAsNonRoot(self):
        """
        Gets the RunAsNonRoot of this V1PodSecurityContext.
        Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.

        :return: The RunAsNonRoot of this V1PodSecurityContext.
        :rtype: bool
        """
        return self._RunAsNonRoot

    @RunAsNonRoot.setter
    def RunAsNonRoot(self, RunAsNonRoot):
        """
        Sets the RunAsNonRoot of this V1PodSecurityContext.
        Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in SecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.

        :param RunAsNonRoot: The RunAsNonRoot of this V1PodSecurityContext.
        :type: bool
        """

        self._RunAsNonRoot = RunAsNonRoot

    @property
    def SupplementalGroups(self):
        """
        Gets the SupplementalGroups of this V1PodSecurityContext.
        A list of groups applied to the first process run in each container, in addition to the container's primary GID.  If unspecified, no groups will be added to any container.

        :return: The SupplementalGroups of this V1PodSecurityContext.
        :rtype: list[int]
        """
        return self._SupplementalGroups

    @SupplementalGroups.setter
    def SupplementalGroups(self, SupplementalGroups):
        """
        Sets the SupplementalGroups of this V1PodSecurityContext.
        A list of groups applied to the first process run in each container, in addition to the container's primary GID.  If unspecified, no groups will be added to any container.

        :param SupplementalGroups: The SupplementalGroups of this V1PodSecurityContext.
        :type: list[int]
        """

        self._SupplementalGroups = SupplementalGroups

    @property
    def FsGroup(self):
        """
        Gets the FsGroup of this V1PodSecurityContext.
        A special supplemental group that applies to all containers in a pod. Some volume types allow the Kubelet to change the ownership of that volume to be owned by the pod:  1. The owning GID will be the FSGroup 2. The setgid bit is set (new files created in the volume will be owned by FSGroup) 3. The permission bits are OR'd with rw-rw 

        :return: The FsGroup of this V1PodSecurityContext.
        :rtype: int
        """
        return self._FsGroup

    @FsGroup.setter
    def FsGroup(self, FsGroup):
        """
        Sets the FsGroup of this V1PodSecurityContext.
        A special supplemental group that applies to all containers in a pod. Some volume types allow the Kubelet to change the ownership of that volume to be owned by the pod:  1. The owning GID will be the FSGroup 2. The setgid bit is set (new files created in the volume will be owned by FSGroup) 3. The permission bits are OR'd with rw-rw 

        :param FsGroup: The FsGroup of this V1PodSecurityContext.
        :type: int
        """

        self._FsGroup = FsGroup

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
