# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: extensions/v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1beta1HorizontalPodAutoscalerStatus(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, ObservedGeneration=None, LastScaleTime=None, CurrentReplicas=None, DesiredReplicas=None, CurrentCPUUtilizationPercentage=None):
        """
        V1beta1HorizontalPodAutoscalerStatus - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'ObservedGeneration': 'int',
            'LastScaleTime': 'datetime',
            'CurrentReplicas': 'int',
            'DesiredReplicas': 'int',
            'CurrentCPUUtilizationPercentage': 'int'
        }

        self.attribute_map = {
            'ObservedGeneration': 'observedGeneration',
            'LastScaleTime': 'lastScaleTime',
            'CurrentReplicas': 'currentReplicas',
            'DesiredReplicas': 'desiredReplicas',
            'CurrentCPUUtilizationPercentage': 'currentCPUUtilizationPercentage'
        }

        self._ObservedGeneration = ObservedGeneration
        self._LastScaleTime = LastScaleTime
        self._CurrentReplicas = CurrentReplicas
        self._DesiredReplicas = DesiredReplicas
        self._CurrentCPUUtilizationPercentage = CurrentCPUUtilizationPercentage

    @property
    def ObservedGeneration(self):
        """
        Gets the ObservedGeneration of this V1beta1HorizontalPodAutoscalerStatus.
        most recent generation observed by this autoscaler.

        :return: The ObservedGeneration of this V1beta1HorizontalPodAutoscalerStatus.
        :rtype: int
        """
        return self._ObservedGeneration

    @ObservedGeneration.setter
    def ObservedGeneration(self, ObservedGeneration):
        """
        Sets the ObservedGeneration of this V1beta1HorizontalPodAutoscalerStatus.
        most recent generation observed by this autoscaler.

        :param ObservedGeneration: The ObservedGeneration of this V1beta1HorizontalPodAutoscalerStatus.
        :type: int
        """

        self._ObservedGeneration = ObservedGeneration

    @property
    def LastScaleTime(self):
        """
        Gets the LastScaleTime of this V1beta1HorizontalPodAutoscalerStatus.
        last time the HorizontalPodAutoscaler scaled the number of pods; used by the autoscaler to control how often the number of pods is changed.

        :return: The LastScaleTime of this V1beta1HorizontalPodAutoscalerStatus.
        :rtype: datetime
        """
        return self._LastScaleTime

    @LastScaleTime.setter
    def LastScaleTime(self, LastScaleTime):
        """
        Sets the LastScaleTime of this V1beta1HorizontalPodAutoscalerStatus.
        last time the HorizontalPodAutoscaler scaled the number of pods; used by the autoscaler to control how often the number of pods is changed.

        :param LastScaleTime: The LastScaleTime of this V1beta1HorizontalPodAutoscalerStatus.
        :type: datetime
        """

        self._LastScaleTime = LastScaleTime

    @property
    def CurrentReplicas(self):
        """
        Gets the CurrentReplicas of this V1beta1HorizontalPodAutoscalerStatus.
        current number of replicas of pods managed by this autoscaler.

        :return: The CurrentReplicas of this V1beta1HorizontalPodAutoscalerStatus.
        :rtype: int
        """
        return self._CurrentReplicas

    @CurrentReplicas.setter
    def CurrentReplicas(self, CurrentReplicas):
        """
        Sets the CurrentReplicas of this V1beta1HorizontalPodAutoscalerStatus.
        current number of replicas of pods managed by this autoscaler.

        :param CurrentReplicas: The CurrentReplicas of this V1beta1HorizontalPodAutoscalerStatus.
        :type: int
        """

        self._CurrentReplicas = CurrentReplicas

    @property
    def DesiredReplicas(self):
        """
        Gets the DesiredReplicas of this V1beta1HorizontalPodAutoscalerStatus.
        desired number of replicas of pods managed by this autoscaler.

        :return: The DesiredReplicas of this V1beta1HorizontalPodAutoscalerStatus.
        :rtype: int
        """
        return self._DesiredReplicas

    @DesiredReplicas.setter
    def DesiredReplicas(self, DesiredReplicas):
        """
        Sets the DesiredReplicas of this V1beta1HorizontalPodAutoscalerStatus.
        desired number of replicas of pods managed by this autoscaler.

        :param DesiredReplicas: The DesiredReplicas of this V1beta1HorizontalPodAutoscalerStatus.
        :type: int
        """

        self._DesiredReplicas = DesiredReplicas

    @property
    def CurrentCPUUtilizationPercentage(self):
        """
        Gets the CurrentCPUUtilizationPercentage of this V1beta1HorizontalPodAutoscalerStatus.
        current average CPU utilization over all pods, represented as a percentage of requested CPU, e.g. 70 means that an average pod is using now 70% of its requested CPU.

        :return: The CurrentCPUUtilizationPercentage of this V1beta1HorizontalPodAutoscalerStatus.
        :rtype: int
        """
        return self._CurrentCPUUtilizationPercentage

    @CurrentCPUUtilizationPercentage.setter
    def CurrentCPUUtilizationPercentage(self, CurrentCPUUtilizationPercentage):
        """
        Sets the CurrentCPUUtilizationPercentage of this V1beta1HorizontalPodAutoscalerStatus.
        current average CPU utilization over all pods, represented as a percentage of requested CPU, e.g. 70 means that an average pod is using now 70% of its requested CPU.

        :param CurrentCPUUtilizationPercentage: The CurrentCPUUtilizationPercentage of this V1beta1HorizontalPodAutoscalerStatus.
        :type: int
        """

        self._CurrentCPUUtilizationPercentage = CurrentCPUUtilizationPercentage

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
