# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: extensions/v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1beta1DeploymentSpec(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Replicas=None, Selector=None, Template=None, Strategy=None, MinReadySeconds=None, RevisionHistoryLimit=None, Paused=None, RollbackTo=None):
        """
        V1beta1DeploymentSpec - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Replicas': 'int',
            'Selector': 'V1beta1LabelSelector',
            'Template': 'V1PodTemplateSpec',
            'Strategy': 'V1beta1DeploymentStrategy',
            'MinReadySeconds': 'int',
            'RevisionHistoryLimit': 'int',
            'Paused': 'bool',
            'RollbackTo': 'V1beta1RollbackConfig'
        }

        self.attribute_map = {
            'Replicas': 'replicas',
            'Selector': 'selector',
            'Template': 'template',
            'Strategy': 'strategy',
            'MinReadySeconds': 'minReadySeconds',
            'RevisionHistoryLimit': 'revisionHistoryLimit',
            'Paused': 'paused',
            'RollbackTo': 'rollbackTo'
        }

        self._Replicas = Replicas
        self._Selector = Selector
        self._Template = Template
        self._Strategy = Strategy
        self._MinReadySeconds = MinReadySeconds
        self._RevisionHistoryLimit = RevisionHistoryLimit
        self._Paused = Paused
        self._RollbackTo = RollbackTo

    @property
    def Replicas(self):
        """
        Gets the Replicas of this V1beta1DeploymentSpec.
        Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1.

        :return: The Replicas of this V1beta1DeploymentSpec.
        :rtype: int
        """
        return self._Replicas

    @Replicas.setter
    def Replicas(self, Replicas):
        """
        Sets the Replicas of this V1beta1DeploymentSpec.
        Number of desired pods. This is a pointer to distinguish between explicit zero and not specified. Defaults to 1.

        :param Replicas: The Replicas of this V1beta1DeploymentSpec.
        :type: int
        """

        self._Replicas = Replicas

    @property
    def Selector(self):
        """
        Gets the Selector of this V1beta1DeploymentSpec.
        Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment.

        :return: The Selector of this V1beta1DeploymentSpec.
        :rtype: V1beta1LabelSelector
        """
        return self._Selector

    @Selector.setter
    def Selector(self, Selector):
        """
        Sets the Selector of this V1beta1DeploymentSpec.
        Label selector for pods. Existing ReplicaSets whose pods are selected by this will be the ones affected by this deployment.

        :param Selector: The Selector of this V1beta1DeploymentSpec.
        :type: V1beta1LabelSelector
        """

        self._Selector = Selector

    @property
    def Template(self):
        """
        Gets the Template of this V1beta1DeploymentSpec.
        Template describes the pods that will be created.

        :return: The Template of this V1beta1DeploymentSpec.
        :rtype: V1PodTemplateSpec
        """
        return self._Template

    @Template.setter
    def Template(self, Template):
        """
        Sets the Template of this V1beta1DeploymentSpec.
        Template describes the pods that will be created.

        :param Template: The Template of this V1beta1DeploymentSpec.
        :type: V1PodTemplateSpec
        """

        self._Template = Template

    @property
    def Strategy(self):
        """
        Gets the Strategy of this V1beta1DeploymentSpec.
        The deployment strategy to use to replace existing pods with new ones.

        :return: The Strategy of this V1beta1DeploymentSpec.
        :rtype: V1beta1DeploymentStrategy
        """
        return self._Strategy

    @Strategy.setter
    def Strategy(self, Strategy):
        """
        Sets the Strategy of this V1beta1DeploymentSpec.
        The deployment strategy to use to replace existing pods with new ones.

        :param Strategy: The Strategy of this V1beta1DeploymentSpec.
        :type: V1beta1DeploymentStrategy
        """

        self._Strategy = Strategy

    @property
    def MinReadySeconds(self):
        """
        Gets the MinReadySeconds of this V1beta1DeploymentSpec.
        Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready)

        :return: The MinReadySeconds of this V1beta1DeploymentSpec.
        :rtype: int
        """
        return self._MinReadySeconds

    @MinReadySeconds.setter
    def MinReadySeconds(self, MinReadySeconds):
        """
        Sets the MinReadySeconds of this V1beta1DeploymentSpec.
        Minimum number of seconds for which a newly created pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready)

        :param MinReadySeconds: The MinReadySeconds of this V1beta1DeploymentSpec.
        :type: int
        """

        self._MinReadySeconds = MinReadySeconds

    @property
    def RevisionHistoryLimit(self):
        """
        Gets the RevisionHistoryLimit of this V1beta1DeploymentSpec.
        The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified.

        :return: The RevisionHistoryLimit of this V1beta1DeploymentSpec.
        :rtype: int
        """
        return self._RevisionHistoryLimit

    @RevisionHistoryLimit.setter
    def RevisionHistoryLimit(self, RevisionHistoryLimit):
        """
        Sets the RevisionHistoryLimit of this V1beta1DeploymentSpec.
        The number of old ReplicaSets to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified.

        :param RevisionHistoryLimit: The RevisionHistoryLimit of this V1beta1DeploymentSpec.
        :type: int
        """

        self._RevisionHistoryLimit = RevisionHistoryLimit

    @property
    def Paused(self):
        """
        Gets the Paused of this V1beta1DeploymentSpec.
        Indicates that the deployment is paused and will not be processed by the deployment controller.

        :return: The Paused of this V1beta1DeploymentSpec.
        :rtype: bool
        """
        return self._Paused

    @Paused.setter
    def Paused(self, Paused):
        """
        Sets the Paused of this V1beta1DeploymentSpec.
        Indicates that the deployment is paused and will not be processed by the deployment controller.

        :param Paused: The Paused of this V1beta1DeploymentSpec.
        :type: bool
        """

        self._Paused = Paused

    @property
    def RollbackTo(self):
        """
        Gets the RollbackTo of this V1beta1DeploymentSpec.
        The config this deployment is rolling back to. Will be cleared after rollback is done.

        :return: The RollbackTo of this V1beta1DeploymentSpec.
        :rtype: V1beta1RollbackConfig
        """
        return self._RollbackTo

    @RollbackTo.setter
    def RollbackTo(self, RollbackTo):
        """
        Sets the RollbackTo of this V1beta1DeploymentSpec.
        The config this deployment is rolling back to. Will be cleared after rollback is done.

        :param RollbackTo: The RollbackTo of this V1beta1DeploymentSpec.
        :type: V1beta1RollbackConfig
        """

        self._RollbackTo = RollbackTo

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
