# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: extensions/v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1beta1NetworkPolicyPort(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Protocol=None, Port=None):
        """
        V1beta1NetworkPolicyPort - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Protocol': 'V1Protocol',
            'Port': 'str'
        }

        self.attribute_map = {
            'Protocol': 'protocol',
            'Port': 'port'
        }

        self._Protocol = Protocol
        self._Port = Port

    @property
    def Protocol(self):
        """
        Gets the Protocol of this V1beta1NetworkPolicyPort.
        Optional.  The protocol (TCP or UDP) which traffic must match. If not specified, this field defaults to TCP.

        :return: The Protocol of this V1beta1NetworkPolicyPort.
        :rtype: V1Protocol
        """
        return self._Protocol

    @Protocol.setter
    def Protocol(self, Protocol):
        """
        Sets the Protocol of this V1beta1NetworkPolicyPort.
        Optional.  The protocol (TCP or UDP) which traffic must match. If not specified, this field defaults to TCP.

        :param Protocol: The Protocol of this V1beta1NetworkPolicyPort.
        :type: V1Protocol
        """

        self._Protocol = Protocol

    @property
    def Port(self):
        """
        Gets the Port of this V1beta1NetworkPolicyPort.
        If specified, the port on the given protocol.  This can either be a numerical or named port on a pod.  If this field is not provided, this matches all port names and numbers. If present, only traffic on the specified protocol AND port will be matched.

        :return: The Port of this V1beta1NetworkPolicyPort.
        :rtype: str
        """
        return self._Port

    @Port.setter
    def Port(self, Port):
        """
        Sets the Port of this V1beta1NetworkPolicyPort.
        If specified, the port on the given protocol.  This can either be a numerical or named port on a pod.  If this field is not provided, this matches all port names and numbers. If present, only traffic on the specified protocol AND port will be matched.

        :param Port: The Port of this V1beta1NetworkPolicyPort.
        :type: str
        """

        self._Port = Port

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
