# coding: utf-8

"""

    No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: extensions/v1beta1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class V1beta1JobStatus(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, Conditions=None, StartTime=None, CompletionTime=None, Active=None, Succeeded=None, Failed=None):
        """
        V1beta1JobStatus - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'Conditions': 'list[V1beta1JobCondition]',
            'StartTime': 'datetime',
            'CompletionTime': 'datetime',
            'Active': 'int',
            'Succeeded': 'int',
            'Failed': 'int'
        }

        self.attribute_map = {
            'Conditions': 'conditions',
            'StartTime': 'startTime',
            'CompletionTime': 'completionTime',
            'Active': 'active',
            'Succeeded': 'succeeded',
            'Failed': 'failed'
        }

        self._Conditions = Conditions
        self._StartTime = StartTime
        self._CompletionTime = CompletionTime
        self._Active = Active
        self._Succeeded = Succeeded
        self._Failed = Failed

    @property
    def Conditions(self):
        """
        Gets the Conditions of this V1beta1JobStatus.
        Conditions represent the latest available observations of an object's current state. More info: http://releases.k8s.io/HEAD/docs/user-guide/jobs.md

        :return: The Conditions of this V1beta1JobStatus.
        :rtype: list[V1beta1JobCondition]
        """
        return self._Conditions

    @Conditions.setter
    def Conditions(self, Conditions):
        """
        Sets the Conditions of this V1beta1JobStatus.
        Conditions represent the latest available observations of an object's current state. More info: http://releases.k8s.io/HEAD/docs/user-guide/jobs.md

        :param Conditions: The Conditions of this V1beta1JobStatus.
        :type: list[V1beta1JobCondition]
        """

        self._Conditions = Conditions

    @property
    def StartTime(self):
        """
        Gets the StartTime of this V1beta1JobStatus.
        StartTime represents time when the job was acknowledged by the Job Manager. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.

        :return: The StartTime of this V1beta1JobStatus.
        :rtype: datetime
        """
        return self._StartTime

    @StartTime.setter
    def StartTime(self, StartTime):
        """
        Sets the StartTime of this V1beta1JobStatus.
        StartTime represents time when the job was acknowledged by the Job Manager. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.

        :param StartTime: The StartTime of this V1beta1JobStatus.
        :type: datetime
        """

        self._StartTime = StartTime

    @property
    def CompletionTime(self):
        """
        Gets the CompletionTime of this V1beta1JobStatus.
        CompletionTime represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.

        :return: The CompletionTime of this V1beta1JobStatus.
        :rtype: datetime
        """
        return self._CompletionTime

    @CompletionTime.setter
    def CompletionTime(self, CompletionTime):
        """
        Sets the CompletionTime of this V1beta1JobStatus.
        CompletionTime represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.

        :param CompletionTime: The CompletionTime of this V1beta1JobStatus.
        :type: datetime
        """

        self._CompletionTime = CompletionTime

    @property
    def Active(self):
        """
        Gets the Active of this V1beta1JobStatus.
        Active is the number of actively running pods.

        :return: The Active of this V1beta1JobStatus.
        :rtype: int
        """
        return self._Active

    @Active.setter
    def Active(self, Active):
        """
        Sets the Active of this V1beta1JobStatus.
        Active is the number of actively running pods.

        :param Active: The Active of this V1beta1JobStatus.
        :type: int
        """

        self._Active = Active

    @property
    def Succeeded(self):
        """
        Gets the Succeeded of this V1beta1JobStatus.
        Succeeded is the number of pods which reached Phase Succeeded.

        :return: The Succeeded of this V1beta1JobStatus.
        :rtype: int
        """
        return self._Succeeded

    @Succeeded.setter
    def Succeeded(self, Succeeded):
        """
        Sets the Succeeded of this V1beta1JobStatus.
        Succeeded is the number of pods which reached Phase Succeeded.

        :param Succeeded: The Succeeded of this V1beta1JobStatus.
        :type: int
        """

        self._Succeeded = Succeeded

    @property
    def Failed(self):
        """
        Gets the Failed of this V1beta1JobStatus.
        Failed is the number of pods which reached Phase Failed.

        :return: The Failed of this V1beta1JobStatus.
        :rtype: int
        """
        return self._Failed

    @Failed.setter
    def Failed(self, Failed):
        """
        Sets the Failed of this V1beta1JobStatus.
        Failed is the number of pods which reached Phase Failed.

        :param Failed: The Failed of this V1beta1JobStatus.
        :type: int
        """

        self._Failed = Failed

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
